### ISSUE TITLE
Turn down the notification of the Season 3 unique

### ISSUE THREAD

**Issue by Balian2483** [eqNj/eqN-PD2-Filter#2]
Hey,

what do you think about turning down the notifications for the season 3 uniques?

Some of them are basically useless, not even good for self use. But I always get baited when I find a ***HERALDIC SHIELD*** thinking its something good but its just useless crap.

My suggestion:     
Cyclopean Roar, Quetzalcoatl, Mage Slayer, Kalan's Legacy can be useful, so I guess it fine to leave them as mid-tier uniques. I personally would demote them to regular unique and not mid-tier as well, but I am sure thats just personal preference.

Sankekur's Fall, True Silver, Tempest are complete trash and should not get any special notifications. Just change them to the regular unique notification that all other uniques get.

Thanks!

**Comment by eqNj** [comment]
Overall, I agree with you. I think they're all mostly just good placeholder uniques. I had them in mid-tier as they were new and quite hyped last season. I will bump down the theatrics on them a little bit for now, but I do still want them to stand out from less useful uniques as they are good at what they do and are still a very special part of what makes PD2 so great. Thank you for your feedback!
