### ISSUE TITLE
can not show rune value

### ISSUE THREAD

**Issue by liugangnhm** [eqNj/eqN-PD2-Filter#4]
![image](https://user-images.githubusercontent.com/743845/148723410-71fa6335-40f0-4231-aed8-56c4085bb0c0.png)

please help!

**Comment by eqNj** [comment]
Enable advanced item display. Follow the attached image for your settings.
![InGameSettings](https://user-images.githubusercontent.com/81050262/148962794-11c2cf1c-005f-49ea-bd13-7075f3c1f162.png)
